###`Q-1:` Create a random 3x4 matrix with value between 0-100. And perform below tasks

    i. Sort this matrix. np.sort()
    ii. Sort this matrix based on values in 2nd column.
    iii. Sort this matrix based on max value in each row.
    iv. Sort based on elements value.


See examples:
```
arr =
    [[92 90 74]
    [ 6 63 93]
    [15 93 96]
    [70 60 48]]
```
```
i. np.sort
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]

ii. based on 2nd column
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]

iii. based on row max- ascending
[[15 93 96]
 [ 6 63 93]
 [92 90 74]
 [70 60 48]]

iv. based on elements value
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]

```

In [30]:
# code here
import numpy as np

arr=np.array([
    [92, 90, 74],
    [6, 63, 93],
    [15, 93, 96],
    [70, 60, 48]
    ])
print(arr)

#1
print(np.sort(arr))
#2
print(arr[arr[:,1].argsort()])
#3
np.array(sorted(arr, key=lambda x:max(x)))[::-1,:]
#4
print(np.sort(arr.flatten()).reshape(4,3))
print(np.sort(arr, axis=None).reshape(4,3))

[[92 90 74]
 [ 6 63 93]
 [15 93 96]
 [70 60 48]]
[[74 90 92]
 [ 6 63 93]
 [15 93 96]
 [48 60 70]]
[[70 60 48]
 [ 6 63 93]
 [92 90 74]
 [15 93 96]]
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]
[[ 6 15 48]
 [60 63 70]
 [74 90 92]
 [93 93 96]]


###`Q-2:` There is an array of marks of 5 students in 4 subjects. Further you are asked to perform below task.
    i. Add marks every student of an extra subject in the same array.
    ii. Add two new students marks in respective 5 subjects.(one subject added in above task)
    iii. Add extra column with sum of all subjects(5-subjects) marks
    iv. Sort the array(non-ascending order) on total marks column--one added in above task. Show top 2 rows.

Note: Change dimension of arrays during concatenation or appending if required.

Given Array-
```
marks = [[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]]

extra_subject = [41, 87, 72, 36, 92]
#Two extra students record-
rec1 = [77, 83, 98, 95, 89]
rec2 = [92, 71, 52, 61, 53]
```

In [58]:
# code here
marks = np.array([[13, 10,  9, 33],
       [63, 46, 90, 42],
       [39, 76, 13, 29],
       [82,  9, 29, 78],
       [67, 61, 59, 36]])

extra_subject = np.array([41, 87, 72, 36, 92]).reshape(5,1)
#Two extra students record-
rec1 = np.array([77, 83, 98, 95, 89]).reshape(1,5)
rec2 = np.array([92, 71, 52, 61, 53]).reshape(1,5)

print(marks, end='\n\n')
print(extra_subject)
print(rec1)
print(rec2, end='\n\n')

com=np.concatenate((marks, extra_subject), axis=1)
print(com, end='\n\n')
com=np.concatenate((com, rec1, rec2), axis=0)
print(com, end='\n\n')
res=np.concatenate((com,np.sum(com, axis=1).reshape(7,1)), axis=1)
print(res, end='\n\n')

print(res[res[:,5].argsort()][::-1,])
res=res[res[:,5].argsort()][::-1,]
print("Top 2 Rows")
print(res[0:2,:])

[[13 10  9 33]
 [63 46 90 42]
 [39 76 13 29]
 [82  9 29 78]
 [67 61 59 36]]

[[41]
 [87]
 [72]
 [36]
 [92]]
[[77 83 98 95 89]]
[[92 71 52 61 53]]

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]]

[[13 10  9 33 41]
 [63 46 90 42 87]
 [39 76 13 29 72]
 [82  9 29 78 36]
 [67 61 59 36 92]
 [77 83 98 95 89]
 [92 71 52 61 53]]

[[ 13  10   9  33  41 106]
 [ 63  46  90  42  87 328]
 [ 39  76  13  29  72 229]
 [ 82   9  29  78  36 234]
 [ 67  61  59  36  92 315]
 [ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]

[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]
 [ 63  46  90  42  87 328]
 [ 67  61  59  36  92 315]
 [ 82   9  29  78  36 234]
 [ 39  76  13  29  72 229]
 [ 13  10   9  33  41 106]]
Top 2 Rows
[[ 77  83  98  95  89 442]
 [ 92  71  52  61  53 329]]


###`Q-3:` Find unique arrays from a 2D array column wise and row wise.
```
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
```
Expected Result-
```
Row Wise
[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]

Col Wise
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]
```

In [62]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
unRW=np.unique(arr, axis=0)
print(unRW)
unCW=np.unique(arr, axis=1)
print(unCW)

[[0 9 1 2 8 8]
 [1 2 3 3 1 1]
 [1 2 3 8 8 8]]
[[1 1 2 3 3]
 [0 8 9 1 2]
 [1 8 2 3 8]
 [1 1 2 3 3]]


###`Q-4:` Flip given 2-D array along both axes at the same time.

In [65]:
# code here
arr = np.array([[1,2,3,3,1,1],
                [0,9,1,2,8,8],
                [1,2,3,8,8,8],
                [1,2,3,3,1,1]])
np.flip(arr, axis=None)

array([[1, 1, 3, 3, 2, 1],
       [8, 8, 8, 3, 2, 1],
       [8, 8, 2, 1, 9, 0],
       [1, 1, 3, 3, 2, 1]])

### `Q-5:` Get row numbers of NumPy array having element larger than X.
```
arr = [[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]]

X = 6
```

In [76]:
# code here
arr = np.array([[1,2,3,4,5],
      [10,-3,30,4,5],
      [3,2,5,-4,5],
      [9,7,3,6,5]])
x=6
print(arr)

np.where(np.any(arr>x, axis=1))

[[ 1  2  3  4  5]
 [10 -3 30  4  5]
 [ 3  2  5 -4  5]
 [ 9  7  3  6  5]]


(array([1, 3]),)

### `Q-6:` How to convert an array of arrays into a flat 1d array?


In [77]:
# These arrays are given.
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

In [82]:
# code here
np.concatenate((arr1, arr2, arr3))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### `Q-7:` You are given a array. You have to find the minimum and maximum array element and remove that from the array.

```python
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
```

In [94]:
# code here
import numpy as np

np.random.seed(400)
arr = np.random.randint(100, 1000, 200).reshape((1, 200))
print(arr)
min_ele=arr.argmin()
max_ele=arr.argmax()
print(arr.min(), arr.max())
arr=np.delete(arr, min_ele, axis=1)
arr=np.delete(arr, max_ele-1, axis=1)
print(arr)
print(arr.min(), arr.max())

[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 137 340 222 215 472 459 617 649 935 956 914 932 645 952
  921 490 527 972 278 307 840 958 246 449 251 957 103 627 920 824 356 825
  173 323 372 960 710 464 244 782 763 635 436 774 171 469 178 458 624 211
  771 270 308 231 952 514 699 702 433 900 373 318 998 265 503 320 230 324
  922 967 620 743 527 117 566 804 123 946 587 227 853 757 944 328 855 930
  325 729 426 514 296 879 575 936 705 209 191 743 510 513 628 559 658 528
  395 525 922 136 496 225 895 975 263 908 420 711 800 976 786 235 930 859
  618 226 695 460 218 483 490 803 621 453 193 607 677 637 728 724 534 748
  291 194 761 875 687 569 228 482 781 554 654 739 885 197 266 228 892 207
  883 588]]
103 998
[[448 563 418 240 507 362 345 236 719 291 298 639 458 387 262 613 267 882
  181 425 790 635 889 818 872 967 277 470 336 920 917 295 557 830 506 385
  353 975 592 997 

### `Q-8:` You are given an arrays. You have to limit this array's elements between 100 to 200. $arr ∈ [100, 700]$. So replace those values accordingly with the minimum and maximum value. Then sort the array and perform the cumulative sum of that array.

In [104]:
# code here
arr=np.random.randint(0, 1000, 500)
arr=np.sort(np.clip(arr, 100, 500))
print(arr)
cumSum=np.cumsum(arr)
print(cumSum) 


[100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100 100
 100 100 100 100 100 100 101 101 103 104 104 104 105 106 110 111 114 114
 116 117 117 129 131 131 132 132 135 136 136 141 141 142 148 150 151 152
 152 159 159 160 160 161 161 164 166 169 170 173 173 180 180 180 180 181
 182 183 183 187 187 192 193 194 195 196 196 196 197 199 201 202 203 203
 207 208 210 210 212 213 213 214 214 214 217 218 219 220 224 224 226 227
 227 232 234 235 235 236 237 237 238 243 245 246 252 254 260 261 261 265
 266 267 268 272 275 276 279 287 287 290 291 292 293 293 294 300 305 308
 311 314 315 315 321 327 329 331 340 343 344 344 345 347 348 349 349 355
 360 361 364 367 368 370 372 374 376 376 377 377 382 383 383 389 399 402
 406 409 409 414 415 417 419 420 424 424 425 425 428 432 432 438 438 439
 440 440 442 444 446 446 449 450 458 458 463 469 474 474 478 483 484 484
 485 491 492 494 496 499 500 500 500 500 500 500 50

### `Q-9:` You are given a array ($arr ∈ [0, 1]$). First you have round off the elements upto 3 decimal places and compare that
- 0th percentile == minimum value of the array
- 100th percentile == maximum value of the array
- also find the difference betwen 51th percenile and 50th percentile values

In [108]:
# code here
arr=np.random.random(100)
arr=np.around(arr, decimals=3)
print(arr)
print("0th percentile == minimum value of the array: ", np.percentile(arr, 0)==arr.min())
print("100th percentile == Maximum value of the array: ", np.percentile(arr, 100)==arr.max())
print("difference betwen 51th percenile and 50th percentile values: ", np.percentile(arr, 51)-np.percentile(arr, 50))

[0.309 0.105 0.267 0.854 0.56  0.463 0.994 0.973 0.495 0.237 0.098 0.505
 0.671 0.268 0.278 0.664 0.093 0.042 0.243 0.481 0.998 0.616 0.941 0.041
 0.038 0.198 0.43  0.956 0.116 0.5   0.907 0.568 0.124 0.305 0.975 0.163
 0.493 0.029 0.317 0.815 0.606 0.581 0.438 0.342 0.449 0.064 0.403 0.603
 0.787 0.426 0.155 0.508 0.899 0.56  0.005 0.448 0.177 0.251 0.266 0.842
 0.482 0.475 0.253 0.08  0.655 0.582 0.46  0.62  0.766 0.315 0.298 0.954
 0.26  0.071 0.128 0.811 0.708 0.359 0.03  0.827 0.127 0.619 0.6   0.351
 0.883 0.511 0.393 0.026 0.824 0.124 0.415 0.986 0.519 0.769 0.433 0.59
 0.842 0.491 0.58  0.653]
0th percentile == minimum value of the array:  True
100th percentile == Maximum value of the array:  True
difference betwen 51th percenile and 50th percentile values:  0.008940000000000003
