<a href="https://colab.research.google.com/github/Saurabh178/Data_Science/blob/master/Task_13_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: In Data Science googling is a very important skill. If you find some difficulties to solve the problem, google it and try to find some clues to solve.**

In [2]:
import numpy as np

###`Q-1` Create a null vector of size 10 but the fifth value which is 1.



In [124]:
#Code here
a=(np.arange(10)==5).astype(int)
print(a)

b=np.nan*np.empty(10)
b[5]=1
b

[0 0 0 0 0 1 0 0 0 0]


array([nan, nan, nan, nan, nan,  1., nan, nan, nan, nan])

###`Q-2` Ask user to input two numbers a, b. Write a program to generate a random array of shape (a, b) and print the array and avg of the array.

In [25]:
#Code here
a=int(input("Enter first number: "))
b=int(input("Enter second number: "))

arr=(np.random.rand(a, b)*100).astype(int)
print(arr, end='\n\n')

np.average(arr)

Enter first number: 3
Enter second number: 4
[[54 50 66 24]
 [19  3 50 63]
 [47 54 39 84]]



46.083333333333336

###`Q-3`Write a function to create a 2d array with 1 on the border and 0 inside. Take 2-D array shape as (a,b) as parameter to function.

Eg.-
```
[[1,1,1,1],
[1,0,0,1],
[1,0,0,1],
[1,1,1,1]]
```

In [126]:
#Code here
a=int(input("Enter number: "))
arr=np.zeros((a-2)**2).reshape(a-2,a-2).astype(int)
arr=np.pad(arr, pad_width=1, constant_values=1)

print(arr)

b=np.ones((4,5))
b[1:-1,1:-1]=0
b

Enter number: 4
[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

###`Q-4` Create a vector of size 10 with values ranging from 0 to 1, both excluded.


In [43]:
#Code here
arr=np.random.rand(10)
arr

array([0.42605073, 0.67745114, 0.31620119, 0.02241937, 0.84222129,
       0.09629687, 0.35531976, 0.80179793, 0.46475461, 0.8247741 ])

###`Q-5` Can you create a identity mattrix of shape (3,4). If yes write code for it.

In [48]:
#Code here
arr=np.identity(4, dtype=int)
arr

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

###`Q-6:` Create a 5x5 matrix with row values ranging from 0 to 4.

In [59]:
#Code here
arr=np.ones((5,5))
arr=(arr*np.arange(5)).astype(int)
arr

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

###`Q-7:`  Consider a random integer (in range 1 to 100) vector with shape `(10,2)` representing coordinates, and coordinates of a point as array is given. Create an array of distance of each point in the random vectros from the given point. Distance array should be interger type.

```
point = np.array([2,3])
```


In [127]:
#code here
point = np.array([2,3])
arr=(np.random.rand(20)*100).astype(int).reshape(10, 2)
print(arr, end='\n\n')

abs=arr-point
print(abs, end='\n\n')

abs=abs**2
print(abs, end='\n\n')
dis=np.sum(abs, axis=1)
print(dis)

[[94 50]
 [46 77]
 [32 87]
 [48 87]
 [73 52]
 [34 91]
 [75 89]
 [24 21]
 [76 65]
 [ 2 63]]

[[92 47]
 [44 74]
 [30 84]
 [46 84]
 [71 49]
 [32 88]
 [73 86]
 [22 18]
 [74 62]
 [ 0 60]]

[[8464 2209]
 [1936 5476]
 [ 900 7056]
 [2116 7056]
 [5041 2401]
 [1024 7744]
 [5329 7396]
 [ 484  324]
 [5476 3844]
 [   0 3600]]

[10673  7412  7956  9172  7442  8768 12725   808  9320  3600]


###`Q-8:` Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [132]:
#Code here
arr=np.random.randint(1,100, (6,7,8))
print(arr)
print(arr[1,5,4])
np.unravel_index(100, (6,7,8))

[[[17 54 23 52  3 55 72 51]
  [12 85 45 77 23 84 90 51]
  [94 31 61 46 62 40  3 30]
  [94 52  6 16 51 39 35 58]
  [75 72 14 18 14 23 49 77]
  [27 32 77 19 43 62  7 12]
  [55 56 58 69 84 47 85 24]]

 [[32 87 83 53 78 68 73 65]
  [42 82 73 76 53 74 13 66]
  [80 63  6 40 34 84 78 93]
  [66 51  5 56 38 53 57 26]
  [93 35 54 11  1 17  4 73]
  [93 68 19 96 88 54 12 18]
  [65 56 68 62 67 83 28 46]]

 [[80 58 74 40 67  3 48 53]
  [70 69  3 49  5 15 95 11]
  [99 65 25  2  9  5 90 51]
  [87  5 21 57 74  4 28 92]
  [29 80 37  1  9 36 71 57]
  [76 66 96  7 71 90 48 71]
  [ 6 64  3 59 96  1 45 97]]

 [[68 14 47 56 83 81 65 89]
  [ 2 26 14 90 23 70 60 78]
  [ 5  6 71 88 58 26  7 76]
  [63 98 22 90 42 51 86 17]
  [ 3 85 22 78 53 62 19 76]
  [80 33 61 82 56 69 66  7]
  [58 21 42 31 23 59 43 78]]

 [[62 15 65 79 26 73 89 35]
  [81 74 57 38 32 11 37 18]
  [ 9 66 23 18 57 62 43 56]
  [13 86  6 69 98 17  9 25]
  [41 94 65 67 83 79  4 13]
  [80 96 78 10 23 30 46 55]
  [62 56 46 23 64 79 90 84]]

 [[29 94 7

(1, 5, 4)

### `Q-9:` Arrays

You are given a space separated list of numbers. Your task is to print a reversed NumPy array with the element type float.



**Input Format:**

A single line of input containing space separated numbers.

**Output Format:**

Print the reverse NumPy array with type float.

**Example 1:**

Input:

```bash
1 2 3 4 -8 -10
```

Output:

```bash
[-10.  -8.   4.   3.   2.   1.]
```

In [140]:
#Code here
arr=np.random.randint(1, 15, (5))
print(arr)

arrRev=arr[::-1]
print(arrRev)

arrRev1=np.flip(arr)
print(arrRev1)

[ 7 11 11 13  2]
[ 2 13 11 11  7]
[ 2 13 11 11  7]


### `Q-10:` Elements count

Count the number of elements of a numpy array.



**Example 1:**

Input:
```bash
np.array([])
```

Output:
```bash
elements_count :  0
```

**Example 2:**

Input:
```bash
np.array([1, 2])
```

Output:
```bash
elements_count :  2
```

In [142]:
#Code here
arr=np.arange(6)
print(arr)
np.size(arr)

[0 1 2 3 4 5]


6

### `Q-11:` Softmax function

Create a Python function to calculate the Softmax of the given numpy 1D array. The function only accepts the numpy 1D array, otherwise raise error.

$$\Large \sigma(\vec z)_i = \frac{e^{z_i}}{\sum_{j=i}^{K}{e^{z_j}}}$$

https://en.wikipedia.org/wiki/Softmax_function



**Example 1:**

Input:
```bash
[86.03331084 37.7285648  48.64908087 87.16563062 38.40852563 37.20006318]
```

Output:
```bash
[2.43733249e-01, 2.56112115e-22, 1.41628284e-17, 7.56266751e-01,
       5.05514197e-22, 1.50974911e-22]
```

**Example 2:**

Input:
```bash
[33.17344305 45.61961654 82.05405781 80.9647098  68.82830233 91.52064278]
```

Output:
```bash
[4.57181035e-26, 1.16249923e-20, 7.73872596e-05, 2.60358426e-05,
       1.39571531e-10, 9.99896577e-01]
```

In [159]:
#Code here
arr=[33.17344305, 45.61961654, 82.05405781, 80.9647098,  68.82830233, 91.52064278]
print(arr, end='\n\n')

sm=np.exp(arr)/np.sum(np.exp(arr))
print(sm)


[33.17344305, 45.61961654, 82.05405781, 80.9647098, 68.82830233, 91.52064278]

[4.57181033e-26 1.16249922e-20 7.73872594e-05 2.60358426e-05
 1.39571531e-10 9.99896577e-01]


### `Q-12:` Vertical stack

Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The function only accepts the numpy array, otherwise raise error.



**Example 1:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]
```

Output:

```bash
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
```

**Example 2:**

Input:
```bash
a= [[0 1 2 3 4]
 [5 6 7 8 9]]

b= [[1 1 1 1 1]
 [1 1 1 1 1]]

c= [[0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

Output:
```bash
[[0.         1.         2.         3.         4.        ]
 [5.         6.         7.         8.         9.        ]
 [1.         1.         1.         1.         1.        ]
 [1.         1.         1.         1.         1.        ]
 [0.10117373 0.1677244  0.73764059 0.83166097 0.48985695]
 [0.44581567 0.13502419 0.55692335 0.16479622 0.61193593]]
```

In [168]:
#Coder here
a=np.random.randint(1,20, (3,4))
print(a)
b=np.random.randint(1,20, (3,4))
print(b)

arr=np.vstack((a, b))
arr

[[16  9 13 15]
 [12  1 15  6]
 [ 8 18  9 17]]
[[ 8 11 15  4]
 [ 8  9  3  4]
 [ 5  1 17  6]]


array([[16,  9, 13, 15],
       [12,  1, 15,  6],
       [ 8, 18,  9, 17],
       [ 8, 11, 15,  4],
       [ 8,  9,  3,  4],
       [ 5,  1, 17,  6]])

### `Q-13:` Dates

Create a python function named **date_array** that accepts two dates as string format and returns a numpy array of dates between those 2 dates. The function only accept 2 strings, otherwise raise error. The date format should be like this only: `2022-12-6`. The end date should be included and for simplicity, choose dates from a same year.



**Example 1:**

Input:
```bash
date_array(start = '2020-09-15', end = '2020-09-25')
```

Output:
```bash
['2020-09-15', '2020-09-16', '2020-09-17', '2020-09-18',
 '2020-09-19', '2020-09-20', '2020-09-21', '2020-09-22',
 '2020-09-23', '2020-09-24', '2020-09-25']
```

**Example 2:**

Input:
```bash
date_array(start = '2022-12-01', end = '2022-12-06')
```

Output:
```bash
['2022-12-01', '2022-12-02', '2022-12-03', '2022-12-04', '2022-12-05', '2022-12-06']
```

**Example 3:**

Input:
```bash
date_array(start = '2020-11-25', end = '2020-11-30')
```

Output:
```bash
['2020-11-25', '2020-11-26', '2020-11-27', '2020-11-28',
 '2020-11-29', '2020-11-30']
```

In [181]:
#Code here
def date_array(start, end):
  if type(start)!=str or type(end)!=str:
    raise TypeError

  total_number_of_days={'01':31, '02':28, '03':31, '04':30, '05':31, '06':30, '07':31, '08':31, '09':30, '10':31, '11':30, '12':31}
  end=end.split('-')
  end_last=int(end[-1])+1

  if total_number_of_days[end[-2]]<end_last:
    diff=end_last-total_number_of_days[end[-2]]
    end[-1]=f'0{diff}' if diff <10 else f'{diff}'
    next_month=int(end[-2])+1
    end[-2]=f'0{next_month}' if next_month <10 else f'{next_month}'
  else:
    end[-1]=f'0{end_last}' if end_last <10 else f'{end_last}'

  end='-'.join(end)
  return np.arange(start, end, dtype='datetime64[D]')

date_array(start = '2020-10-25', end = '2020-12-30')

array(['2020-10-25', '2020-10-26', '2020-10-27', '2020-10-28',
       '2020-10-29', '2020-10-30', '2020-10-31', '2020-11-01',
       '2020-11-02', '2020-11-03', '2020-11-04', '2020-11-05',
       '2020-11-06', '2020-11-07', '2020-11-08', '2020-11-09',
       '2020-11-10', '2020-11-11', '2020-11-12', '2020-11-13',
       '2020-11-14', '2020-11-15', '2020-11-16', '2020-11-17',
       '2020-11-18', '2020-11-19', '2020-11-20', '2020-11-21',
       '2020-11-22', '2020-11-23', '2020-11-24', '2020-11-25',
       '2020-11-26', '2020-11-27', '2020-11-28', '2020-11-29',
       '2020-11-30', '2020-12-01', '2020-12-02', '2020-12-03',
       '2020-12-04', '2020-12-05', '2020-12-06', '2020-12-07',
       '2020-12-08', '2020-12-09', '2020-12-10', '2020-12-11',
       '2020-12-12', '2020-12-13', '2020-12-14', '2020-12-15',
       '2020-12-16', '2020-12-17', '2020-12-18', '2020-12-19',
       '2020-12-20', '2020-12-21', '2020-12-22', '2020-12-23',
       '2020-12-24', '2020-12-25', '2020-12-26', '2020-

###`Q-14:` Subtract the mean of each row from a matrix.

In [189]:
#code here
arr=np.random.randint(1,10, (5,4))
arr
x=np.mean(arr, axis=1, keepdims=True)
arr=arr-x
arr

array([[ 1.25,  2.25, -1.75, -1.75],
       [-0.75,  1.25, -0.75,  0.25],
       [ 3.25,  2.25, -1.75, -3.75],
       [ 3.  ,  3.  , -4.  , -2.  ],
       [ 2.5 , -1.5 ,  1.5 , -2.5 ]])

###`Q-15:` Swap column-1 of array with column-2 in the array.

In [199]:
#Code here
arr=np.arange(1,13).reshape(3,4)
print(arr, end='\n\n')
arr=arr[:, [0, 2, 1, 3]]
print(arr, end='\n\n')


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  3  2  4]
 [ 5  7  6  8]
 [ 9 11 10 12]]



###`Q-16:` Replace odd elements in arrays with -1.

In [205]:
#Code here
a=np.arange(1,13).reshape(4,3)
print(a, end='\n\n')
a[a%2==1]=-1
print(a, end='\n\n')

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]
 [10 -1 12]]



array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

###`Q-17:` Given two arrays of same shape make an array of max out of two arrays. (Numpy way)
```
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])

Result-> [6 3 1 7 8]
```

In [201]:
#Code here
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
arr=np.vstack((a,b))
res=np.max(arr, axis=0)
res

array([6, 3, 1, 7, 8])

###`Q-18` Answer below asked questions on given array:
1. Fetch Every alternate column of the array
2. Normalise the given array

https://en.wikipedia.org/wiki/Normalization_(statistics)

There are different form of normalisation for this question use below formula.

$$\large X_{normalized} = \frac{X - X_{min}}{X_{max} - X_{min}}$$

```python
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
```


In [210]:
# Given
arr1=np.random.randint(low=1, high=10000, size=40).reshape(8,5)
print(arr1, end='\n\n')
arr1=arr1[:, ::2]
print(arr1, end='\n\n')

x=(arr1-arr1.min())/(arr1.max()-arr1.min())
print(x, end='\n\n')

[[9711 8898 1165 3208 1810]
 [4739  109 6924 3796 2549]
 [3068 3138 2591 7895 5164]
 [8148  409 5026 5094 4577]
 [5688 4306 4502 7928 1934]
 [6480 4365 5455 3494 6742]
 [4920 6066 4820 7260 7446]
 [1054 5917 2789 7996 7643]]

[[9711 1165 1810]
 [4739 6924 2549]
 [3068 2591 5164]
 [8148 5026 4577]
 [5688 4502 1934]
 [6480 5455 6742]
 [4920 4820 7446]
 [1054 2789 7643]]

[[1.         0.01282199 0.08732817]
 [0.42566709 0.67806399 0.17269262]
 [0.2326441  0.17754418 0.47476031]
 [0.81945247 0.45881945 0.40695391]
 [0.53528936 0.3982904  0.10165184]
 [0.62677602 0.50837473 0.65704055]
 [0.44657503 0.43502368 0.73836202]
 [0.         0.20041585 0.76111817]]



In [ ]:
#Code here

###`Q-19:` Write a function which will accept 2 arguments.
First: A 1D numpy array arr

Second: An integer n {Please make sure n<=len(arr)}

Output: The output should be the nth largest item out of the array
```
# Example1 : arr=(12,34,40,7,1,0) and n=3, the output should be 12
# Example2 : arr=(12,34,40,7,1,0) and n=1, the output should be 40
```

In [228]:
#Code here
def nLargest(arr, n):
  if n>len(arr):
    raise IndexError("Out of Range")
  arr.sort()
  return arr[-n]

nLargest(np.array([2,6,4,1,8]), 2)

6

###`Q-20:` Create the following pattern without hardcoding. Use only numpy functions and the below input array a.
```
# Input: a = np.array([1,2,3])
# Output: array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
```

In [229]:
#code here
a = np.array([1,2,3])
b=np.repeat(a, 3)
c=np.tile(a,3)
a=np.hstack((b,c))
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])